### ISSUE TITLE
[Data Update]: UW Madison fee update

### ISSUE THREAD

**Issue by shuyaoli** [CSStipendRankings/CSStipendRankings#100]
> Please duplicate the block below for each institution you want to add or update.

## Institution name: 

* [x] This updates an existing institution. 

- **Annual Out-of-pocket Fees (and Health Insurance) Charged by University (USD)**:
Segregated fee: $1561.48, or $1951.85 if the student enrolled in the summer semester (Summer --enrollment is not required unless the student is funded during the summer or doing CPT internship)
International student fee: $200, or $300 if the student is enrolled in the summer semester
Health insurance cost: $728 for funded students, $1788 for students without funding

- **Source of the stipend and fee data (e.g., your own data point, a link to an official website, etc.)**: 
segregated fee: https://bursar.wisc.edu/tuition-and-fees/segregated-fees
International student fee: personal data point
healthcare cost for funded students (without dental): https://uwservice.wisconsin.edu/premiums/index.php
healthcare cost for students without funding: https://www.uhs.wisc.edu/wp-content/uploads/2023/07/SHIP_2023_International-Student_Snapshot_of_Benefits_FINAL.pdf

**Comment by mjc0608** [comment]
So what's the maximum possible fee?

**Comment by mjc0608** [comment]
"Summer --enrollment is not required unless the student is funded during the summer or doing CPT internship". Based on my understanding, this basically says the fee is required.

So I will use 1951.85 + 300 + 1788.

**Comment by mjc0608** [comment]
This is updated
