### ISSUE TITLE
[Data Update]: UW CSE

### ISSUE THREAD

**Issue by mickel-liu** [CSStipendRankings/CSStipendRankings#102]
> Please duplicate the block below for each institution you want to add or update.

## Institution name: 

* [x] This updates an existing institution. 

- **Annual Stipend Amount (USD, both Pre-Qualification and Post-Qualification if different)**: 

$31,626, ($3,514 per month).

- **Annual Out-of-pocket Fees (and Health Insurance) Charged by University (USD)**:

approximately $265 per quarter

- **Summer Funding Guarantee**: (yes/no/don't know)

No, but it varies depending on the advisors. But I heard doubling the pay is normal.

- **Source of the stipend and fee data (e.g., your own data point, a link to an official website, etc.)**: 

Quoted from my own offer letter:

> Allen School Ph.D. students are guaranteed a 50% FTE position as a Research Assistant (RA)
or Teaching Assistant (TA) in the first three (3) academic years.

>The effective dates of your position for the first year are from September 16, 2024 to June
15, 2025, with a current monthly salary of **$3,514 ($31,626/academic year)**. All of your
tuition will be covered. During the quarters in which you have an RA or TA position, you will
be responsible for paying required fees of approximately $265 per quarter (Services and
Activities Fee, Intramural Athletics Building Bond Fee). The total value of this annual
support is $72,855. Tuition, salary, and fees are typically adjusted in July of each year.

- **Additional Comments (Optional)**: 

I don't know where the current number "46844" came from, but I guess it includes the summer funding which I have no data point yet.

**Comment by mjc0608** [comment]
The number includes summer funding, and was previously reported in a google form submission.
