### ISSUE TITLE
[Data Update]: Carnegie Mellon

### ISSUE THREAD

**Issue by JamesGallicchio** [CSStipendRankings/CSStipendRankings#103]
> Please duplicate the block below for each institution you want to add or update.

## Institution name: Carnegie Mellon University

* [X] This updates an existing institution.

- **Annual Stipend Amount (USD, both Pre-Qualification and Post-Qualification if different)**: 41,460

- **Annual Local Living Wage (USD)**: 43,957

  - **Link to the [MIT Living Wage Calculator](http://livingwage.mit.edu/)**: https://livingwage.mit.edu/metros/38300

    > Note: Please use The number in `Typical Expenses -> Required annual income before taxes -> 1 Adult & 0 Children` as the annual local living wage.

- **Annual Out-of-pocket Fees (and Health Insurance) Charged by University (USD)**: $0

- **Summer Funding Guarantee**: No

- **Source of the stipend and fee data (e.g., your own data point, a link to an official website, etc.)**: my data

- **Additional Comments (Optional)**:

I listed the stipend for *next* academic year (24-25), which is higher than the 23-24 stipend ($39,960).

Summer funding is handled by each department separately, but across SCS in general summer funding is not guaranteed. My department has claimed to guarantee summer funding, but students of advisors who do not have funding are generally expected (/heavily pushed) to get internships.

**Comment by mjc0608** [comment]
Updated and removed the guaranteed label. It would be great if you can list the source (e.g., email/website), and how much of these stipend are from summer funding.
