### ISSUE TITLE
[Data Update]: University at Buffalo

### ISSUE THREAD

**Issue by cwmiller1** [CSStipendRankings/CSStipendRankings#113]
> Please duplicate the block below for each institution you want to add or update.

## Institution name: University at Buffalo

* [ ] This updates an existing institution. 

- **Annual Stipend Amount (USD, both Pre-Qualification and Post-Qualification if different)**: $29,900

- **Annual Local Living Wage (USD)**: $43,963

  - **Link to the [MIT Living Wage Calculator](http://livingwage.mit.edu/)**: https://livingwage.mit.edu/counties/36029

    > Note: Please use The number in `Typical Expenses -> Required annual income before taxes -> 1 Adult & 0 Children` as the annual local living wage.

- **Annual Out-of-pocket Fees (and Health Insurance) Charged by University (USD)**: $3,300

- **Summer Funding Guarantee**: (yes/no/don't know) no

- **Source of the stipend and fee data (e.g., your own data point, a link to an official website, etc.)**: 
- https://www.buffalo.edu/grad/explore/funding/phd-level-funding.html#:~:text=PhD%20Excellence%20Initiative,-The%20PhD%20Excellence&text=competitive%20over%20time.-,All%20full%2Dtime%2C%20fully%20funded%20PhD%20students%20on%2010%2D,as%20the%20campus%20minimum%20stipend
- https://financialaid.buffalo.edu/costs/

- **Additional Comments (Optional)**: 
- Full-time, fully funded PhD students on 12-month appointments receive $29,900 as the campus minimum stipend.
- All full-time, fully funded PhD students on 10-month TA/RA/GA appointments receive a minimum of $23,000 for academic year stipends.
- The total fees are $3,300 (most covered for PhD students by the PhD excellence scholarship)

**Comment by mjc0608** [comment]
updated
