### ISSUE TITLE
[Data Update]: University at Buffalo

### ISSUE THREAD

**Issue by cwmiller1** [CSStipendRankings/CSStipendRankings#116]
> Please duplicate the block below for each institution you want to add or update.

## Institution name: University at Buffalo

* [x] This updates an existing institution. 

- **Annual Stipend Amount (USD, both Pre-Qualification and Post-Qualification if different)**: $29,900

- **Annual Local Living Wage (USD)**: $21,762

  - **Link to the [MIT Living Wage Calculator](http://livingwage.mit.edu/)**: 
  
https://financialaid.buffalo.edu/costs/

    > Note: Please use The number in `Typical Expenses -> Required annual income before taxes -> 1 Adult & 0 Children` as the annual local living wage.

- **Annual Out-of-pocket Fees (and Health Insurance) Charged by University (USD)**: $3,300

- **Summer Funding Guarantee**: (yes/no/don't know) no

- **Source of the stipend and fee data (e.g., your own data point, a link to an official website, etc.)**: 

https://www.buffalo.edu/grad/explore/funding/phd-level-funding.html#:~:text=PhD%20Excellence%20Initiative,-The%20PhD%20Excellence&text=competitive%20over%20time.-,All%20full%2Dtime%2C%20fully%20funded%20PhD%20students%20on%2010%2D,as%20the%20campus%20minimum%20stipend

https://financialaid.buffalo.edu/costs/

- **Additional Comments (Optional)**: 

Full-time, fully funded PhD students on 12-month appointments receive $29,900 as the campus minimum stipend.

All full-time, fully funded PhD students on 10-month TA/RA/GA appointments receive a minimum of $23,000 for academic year stipends.

The total fees are $3,300 (most covered for PhD students by the PhD excellence scholarship)

We adapt Annual Local Living Wage (USD) from the University at Buffalo Office of Financial Aid -> Financial Aid Cost of Attendance (COA) for New York State resident and non-resident graduate students.  On website:

https://financialaid.buffalo.edu/costs/

"Graduate 2024-2025 Cost of Attendance Breakdown" line items detail:

Living Expense Room: $11,422

Living Expense Meals: $4,158

Books, Course Materials, Supplies, and Equipment: $1,500

Personal Expenses: $2,106

Transportation Expenses: $2,576

TOTAL: $21,762

**Comment by mjc0608** [comment]
We do not take the living cost estimated by the university as these costs are usually underestimated by the university. We use MIT living wage calculator as the solo source of living cost. If you think the living cost is incorrectly estimated by MIT, please contact the researchers there.

Sorry, this date update request is rejected.
