### ISSUE TITLE
[Data Update]: New Jersey Institute of Technology

### ISSUE THREAD

**Issue by ikoutis** [CSStipendRankings/CSStipendRankings#117]
> Please duplicate the block below for each institution you want to add or update.

## Institution name:  New Jersey Institute of Technology

* [x] This updates an existing institution. 

- **Annual Stipend Amount (USD, both Pre-Qualification and Post-Qualification if different)**:  $39,342

- **Annual Local Living Wage (USD)**: $47,834

  - **Link to the [MIT Living Wage Calculator](http://livingwage.mit.edu/)**:   https://livingwage.mit.edu/counties/34013

    > Note: Please use The number in `Typical Expenses -> Required annual income before taxes -> 1 Adult & 0 Children` as the annual local living wage.

- **Annual Out-of-pocket Fees (and Health Insurance) Charged by University (USD)**: 0

- **Summer Funding Guarantee**:  yes
The current contract of the adjunct/PhD students/postdocs union (UCAN) with NJIT: [UCANGSREMOA.pdf](https://github.com/CSStipendRankings/CSStipendRankings/files/15397052/Copy.of.UCANGSREMOA.pdf)

- **Source of the stipend and fee data (e.g., your own data point, a link to an official website, etc.)**: 

- **Additional Comments (Optional)**:  The attached contract affects all PhD students at NJIT, including CS students. The quoted **minimum** amount applies to the coming academic year (2024-2025), beginning July 1st. The stipend current year 2023-2024 was also retroactively raised to $35,758. These amounts can be found in Article III (p.3) of the attached document. The new contract was [ratified](https://rutgersaaup.org/victory-at-njit-our-sister-union-ucan-has-tentative-agreements/) in January 2024, and it can be independently verified by contacting [UCAN](https://ucanaft.org/ucan-executive-committee-2022-2023/). Article III states that the amounts are for the calendar year, defined in article IV as the period from July 1st to June 30. Article IV also specifies that after the first year, continuing Graduate Employees shall be appointed on a calendar year basis -- the first year is an exception because students join in the end of August.

**Comment by mjc0608** [comment]
Can you add some information about summer funding? E.g., how much of the funding of the summer is guaranteed?

**Comment by mjc0608** [comment]
For now, I'm using 4 month as summer and all months with the same stipend.

**Comment by ikoutis** [comment]
The stated amount includes summer, and it is guaranteed to all students who are present in the summer.  For students that take internship positions the total amount is what the attached contract also specifies in page 2 (as 'academic year'), and it is $34,211.  This corresponds roughly to 10.5 months, modulo some biweekly check calculations.  For the year 25-26 the amounts will be $46K and $40K, which is the same ratio. So, 'summer time' is 2.5 months, it is guaranteed, *unless* of course the student wants to be employed in an internship position.
