### ISSUE TITLE
[Data Update]: 

### ISSUE THREAD

**Issue by Melissa1181** [CSStipendRankings/CSStipendRankings#129]
> Please duplicate the block below for each institution you want to add or update.

## Institution name: 

* [ ] This updates an existing institution. 

- **Annual Stipend Amount (USD, both Pre-Qualification and Post-Qualification if different)**: 

- **Annual Local Living Wage (USD)**:

  - **Link to the [MIT Living Wage Calculator](http://livingwage.mit.edu/)**: 

    > Note: Please use The number in `Typical Expenses -> Required annual income before taxes -> 1 Adult & 0 Children` as the annual local living wage.

- **Annual Out-of-pocket Fees (and Health Insurance) Charged by University (USD)**:

- **Summer Funding Guarantee**: (yes/no/don't know)

- **Source of the stipend and fee data (e.g., your own data point, a link to an official website, etc.)**: 

- **Additional Comments (Optional)**:

**Comment by mjc0608** [comment]
Close due to missing school information. If you want to update an entry, reopen it anytime.
