### ISSUE TITLE
[Data Update]: University of California, Santa Barbara

### ISSUE THREAD

**Issue by seanliu96** [CSStipendRankings/CSStipendRankings#14]
> Please duplicate the block below for each institution you want to add or update.

## Institution name: University of California, Santa Barbara

* [x] This updates an existing institution. 

- **Annual Stipend Amount (USD, both Pre-Qualification and Post-Qualification if different)**: 40,000

- **Annual Local Living Wage (USD)**: 51,681

  - **Link to the [MIT Living Wage Calculator](http://livingwage.mit.edu/)**: [Santa Barbara](https://livingwage.mit.edu/counties/06083)

    > Note: Please use The number in `Typical Expenses -> Required annual income before taxes -> 1 Adult & 0 Children` as the annual local living wage.

- **Annual Out-of-pocket Fees Charged by University (USD)**: 0

- **Source of the stipend and fee data (e.g., your own data point, a link to an official website, etc.)**: official offer

- **Additional Comments (Optional)**: do not know the stipend after qualification

**Comment by TonyZhangND** [comment]
Updated
