### ISSUE TITLE
[Data Update]: UMass Amherst

### ISSUE THREAD

**Issue by brendano** [CSStipendRankings/CSStipendRankings#19]
> Please duplicate the block below for each institution you want to add or update.

## Institution name: UMass Amherst

- **Annual Stipend Amount (USD, both Pre-Qualification and Post-Qualification if different)**:  $37,533

- **Annual Local Living Wage (USD)**: $33,866

  - **Link to the [MIT Living Wage Calculator](http://livingwage.mit.edu/)**:  https://livingwage.mit.edu/counties/25015

    > Note: Please use The number in `Typical Expenses -> Required annual income before taxes -> 1 Adult & 0 Children` as the annual local living wage.

- **Annual Out-of-pocket Fees Charged by University (USD)**: ???

- **Source of the stipend and fee data (e.g., your own data point, a link to an official website, etc.)**: 

Stipend data is supplied by the College of Information and Computer Sciences

- **Additional Comments (Optional)**: 

12-month stipend = $37,533

Summer funding is guaranteed for the first summer; after that the dept guarantees just fall/spring (summer funding at that point is typically subject to RAship availability, typically from an advisor).

The calculation is based on the current CICS stipend hourly rate in spring 2023 ($36.09), and doesn't include future raises - the grad student union ([GEO](https://www.geouaw.org/)) negotiates contracts typically with yearly or so raises built in, but I don't have information on what the next contract will include.  More information on the current contract, from GEO: https://www.geouaw.org/geo-contract/

I'm personally curious whether unionized graduate students make a difference across institutions (I don't think we're the only one on the list? But not many?)

Cost of living = $33,866
From 1 adult + 0 children in Hampshre County MA from https://livingwage.mit.edu/counties/25015

Fees = ???
I don't know this.

I dunno if this is enough information for you folks to include?

**Comment by mjc0608** [comment]
added
