### ISSUE TITLE
[Data Update]: UT Austin stipends

### ISSUE THREAD

**Issue by gregdurrett** [CSStipendRankings/CSStipendRankings#30]
> Please duplicate the block below for each institution you want to add or update.

## Institution name: 

* [X] This updates an existing institution. 

- **Annual Stipend Amount (USD, both Pre-Qualification and Post-Qualification if different)**: 38,400

- **Annual Local Living Wage (USD)**: [use what's on the site currently]

  - **Link to the [MIT Living Wage Calculator](http://livingwage.mit.edu/)**: 

    > Note: Please use The number in `Typical Expenses -> Required annual income before taxes -> 1 Adult & 0 Children` as the annual local living wage.

- **Annual Out-of-pocket Fees Charged by University (USD)**: [use what's on the site currently]

- **Source of the stipend and fee data (e.g., your own data point, a link to an official website, etc.)**: 

I am a CS professor at UT Austin. We raised our stipends to $3200/mo. The language in our 2023 offer letters was:
"""
At minimum, the department guarantees that you will be supported as a Teaching Assistant in the fall and spring semesters, earning a monthly stipend of $3,200 per month for nine (9) months in each academic year in return for serving as a TA in a CS class. However, once you begin working with an advisor, the advisor may be able to offer you a GRA. This would relieve you from any teaching-related duties and may come with a higher stipend. [...]
"""
Furthermore, a similar number ($38,000) is verified here:
https://jeffhuang.com/computer-science-open-data/#verified-computer-science-phd-stipends

- **Additional Comments (Optional)**: Thanks for putting this together! I support advocating for higher stipends for graduate students everywhere, and I think resources like this are very valuable! We can all aspire to be Princeton... :)

**Comment by mjc0608** [comment]
Hi Greg,

I will update the data. May I also ask whether UT Austin has guaranteed summer funding?

Best,
Jiacheng

**Comment by mguthaus** [comment]
If summer funding isn't guaranteed, this number should be 28800.

**Comment by mjc0608** [comment]
Thanks for this information.
