### ISSUE TITLE
[Data Update]: Add UCLA

### ISSUE THREAD

**Issue by khosravipasha** [CSStipendRankings/CSStipendRankings#32]
> Please duplicate the block below for each institution you want to add or update.

## Institution name: University of California, Los Angeles (UCLA)

* [ ] This updates an existing institution. 

- **Annual Stipend Amount (USD, both Pre-Qualification and Post-Qualification if different)**:  $42,600

- **Annual Local Living Wage (USD)**:  $44,783

  - **Link to the [MIT Living Wage Calculator](http://livingwage.mit.edu/)**: 

    > Note: Please use The number in `Typical Expenses -> Required annual income before taxes -> 1 Adult & 0 Children` as the annual local living wage.

- **Annual Out-of-pocket Fees Charged by University (USD)**: $180

- **Source of the stipend and fee data (e.g., your own data point, a link to an official website, etc.)**:  https://livingwage.mit.edu/metros/31080

- **Additional Comments (Optional)**: 
    - Out of pocket fees around $60 per quarter, for Fall, Spring, Winter (Used to be $150 per quarter)
    - Yearly Stipend (around 12 * 3550) assuming summer included as usual, sometimes could be more during summer.

**Comment by mjc0608** [comment]
>Yearly Stipend (around 12 * 3550) assuming summer included as usual, sometimes could be more during summer
Does this imply that UCLA has a summer funding guarantee? If so we will add a tag there.

**Comment by mguthaus** [comment]
Should summer be included if it is not guaranteed? This isn't clear in the methodology. Some schools are reporting differently.

**Comment by mjc0608** [comment]
We are actually debating about it. One way do deal with this is to make it an option that users can turn it on or off, but that requires some implementation and additional data about the summer income.

**Comment by khosravipasha** [comment]
I am not sure about the summer guarantee.
During normal quarters can do at most 50% appointment (so multiply by half), during summer students can do up to 100% appoitment (the 100% is not guaranteed, but not sure if the 50% for summer is guaranteed).  

I am graduaing and there was a lot of changes recently that I might not know about. Also, the numbers also differ per quarter If you Teaching Assistant, or Graduate Student Researcher. The number I mentioned should be relatively close to the average.

- https://www.ucop.edu/academic-personnel-programs/_files/2022-23/april-2023-ase-gsr-postoc-salary-scales/t22.pdf
- https://www.ucop.edu/academic-personnel-programs/_files/2022-23/april-2023-ase-gsr-postoc-salary-scales/t18.pdf

**Comment by mjc0608** [comment]
@khosravipasha can you point out where the 3550/month data is from? These links seem to suggest a higher stipend.

**Comment by khosravipasha** [comment]
During the year for Fall, Spring and Winter is 50% appoitments so have to multiply by 0.5. Summar is also usually 50% but can be up to 100% (its depends on PI)

![image](https://user-images.githubusercontent.com/2780093/236649648-9b8c7267-aedd-4029-a6f8-270bd362a0d1.png)

**Comment by mjc0608** [comment]
Got it. However, although this form is from the UCOP website, it does not show UCLA on it and it's unclear which increment is used. I think the stipend listed on the website is already updated, but we are not able to give a blue checkmark.
