### ISSUE TITLE
[Data Update]: correcting the local living wage of UT Austin

### ISSUE THREAD

**Issue by SaugataGhose** [CSStipendRankings/CSStipendRankings#36]
> Please duplicate the block below for each institution you want to add or update.

## Institution name: The University of Texas at Austin

* [ ] This updates an existing institution. 

- **Annual Stipend Amount (USD, both Pre-Qualification and Post-Qualification if different)**: 

- **Annual Local Living Wage (USD)**: 38,171 

  - **Link to the [MIT Living Wage Calculator](http://livingwage.mit.edu/)**: https://livingwage.mit.edu/counties/48453

    > Note: Please use The number in `Typical Expenses -> Required annual income before taxes -> 1 Adult & 0 Children` as the annual local living wage.

- **Annual Out-of-pocket Fees (and Health Insurance) Charged by University (USD)**:

- **Summer Funding Guarantee**:

- **Source of the stipend and fee data (e.g., your own data point, a link to an official website, etc.)**: 

- **Additional Comments (Optional)**: the current value incorrectly uses Austin County, TX - the city of Austin is in Travis County, and Austin County is unrelated

**Comment by mjc0608** [comment]
done

**Comment by mjc0608** [comment]
Also BTW, do you have guaranteed summer funding at UT Austin?

**Comment by JiyangZhang** [comment]
> Also BTW, do you have guaranteed summer funding at UT Austin?

I have never heard about this.
