### ISSUE TITLE
[Data Update]: NSF GRFP and DOE CSGF

### ISSUE THREAD

**Issue by sree314** [CSStipendRankings/CSStipendRankings#38]
> Please duplicate the block below for each institution you want to add or update.

## Institution name: NSF Graduate Research Fellowship

* [ ] This updates an existing institution. 

- **Annual Stipend Amount (USD, both Pre-Qualification and Post-Qualification if different)**: 37000

- **Annual Local Living Wage (USD)**: Varies

  - **Link to the [MIT Living Wage Calculator](http://livingwage.mit.edu/)**: N/A 

    > Note: Please use The number in `Typical Expenses -> Required annual income before taxes -> 1 Adult & 0 Children` as the annual local living wage.

- **Annual Out-of-pocket Fees (and Health Insurance) Charged by University (USD)**: 0

- **Summer Funding Guarantee**: Yes

- **Source of the stipend and fee data (e.g., your own data point, a link to an official website, etc.)**: https://www.nsf.gov/pubs/2022/nsf22614/nsf22614.htm

- **Additional Comments (Optional)**: The NSF pays up to $12K in fees. The living cost obviously varies based on Institution. FWIW, many institutions would top up the GRFP to meet their existing stipend if their stipend is higher than NSF. 

## Institution name: DOE Computational Science Graduate Fellowship

* [ ] This updates an existing institution. 

- **Annual Stipend Amount (USD, both Pre-Qualification and Post-Qualification if different)**: 45000

- **Annual Local Living Wage (USD)**: Varies

  - **Link to the [MIT Living Wage Calculator](http://livingwage.mit.edu/)**: N/A 

    > Note: Please use The number in `Typical Expenses -> Required annual income before taxes -> 1 Adult & 0 Children` as the annual local living wage.

- **Annual Out-of-pocket Fees (and Health Insurance) Charged by University (USD)**: 0

- **Summer Funding Guarantee**: Yes

- **Source of the stipend and fee data (e.g., your own data point, a link to an official website, etc.)**: https://www.krellinst.org/csgf/about-doe-csgf/benefits-opportunities

- **Additional Comments (Optional)**: The DOE pays all mandatory fees (including tuition). The living cost obviously varies based on Institution. As with the GRFP, many institutions may top up the CSGF to meet their existing stipend if their stipend is higher than DOE CSGF

**Comment by TonyZhangND** [comment]
@mjc0608 I'm hesitant to add this as it's a rare opportunity for select students

**Comment by mjc0608** [comment]
This data point looks interesting. @shibo-chen @jiong-zhu @pyjhzwh 

My concerns are 1) NSF/DOE are technically not universities, and 2) we have no idea how to deal with the living wage.

**Comment by TonyZhangND** [comment]
I think a good solution is to add info/link on our website to such sources of funding, instead of including them in the ranking

**Comment by sree314** [comment]
I know these entries complicate the data model, but I advocate adding them so people actually know about these fellowships and people at universities can compare against them.

I agree they're not available to all students.

Links are fine as a first step, for sure.

**Comment by noah-curran** [comment]
I agree that these data points are important to add, but there should be a filter to include them. The default, in my opinion, should be that they are toggled off.

**Comment by noah-curran** [comment]
Hi all, I'm currently working on a good way to display this data on https://github.com/noah-curran/CSStipendRankings/tree/fellowships. Feel free to provide feedback.

**Comment by noah-curran** [comment]
> My concerns are 1) NSF/DOE are technically not universities, and 2) we have no idea how to deal with the living wage.

@mjc0608 I believe my solution in #45 addresses both of these concerns, but please let me know if you still have any ways to improve what I've proposed.

**Comment by sree314** [comment]
@noah-curran , great work! I would mark this issue as fixed. 

Wonderful work adding all those other fellowships as well, some of which I wasn't aware about!

**Comment by mjc0608** [comment]
I will close this issue since it's resolved by #45

**Comment by mjc0608** [comment]
Can I consider the data for these fellowship verified? If so I will add the blue checkmark for them.

**Comment by jiong-zhu** [comment]
I think so. Both URLs provided are official websites and I have verified the numbers again. 

BTW, is it possible to add sorting to the dropdown box that selects the living cost baseline for fellowship? The current dropdown box uses the CSV order and does not sort it, which can make people hard to find their desired institution.

**Comment by noah-curran** [comment]
> Can I consider the data for these fellowship verified?

@mjc0608 Based on my look at the webpages, they looked OK to me. My only concern is whether there are limitations to the fees that the fellowships claim to cover. I don't have any data points to confirm/deny this concern, so we may need to wait until someone raises an issue about it.

**Comment by mjc0608** [comment]
Ok I guess I will mark it as verified for now
