### ISSUE TITLE
Probably also add some tax information ?

### ISSUE THREAD

**Issue by Youngzt998** [CSStipendRankings/CSStipendRankings#50]
It may be extremely hard to collect such information since different states have different rates, and international/non-international students from different countries will have different tax rules & treaties. Some universities may give combinations of fellowship and stipend. All of those can result in totally different tax rates. 

But it should really help more if the real after-tax & after-fee amount can be shown.

**Comment by mjc0608** [comment]
US has a really complex tax system, which makes implementing this hard. For now, I don't think it's our priority. However, we are definitely willing to merge it into the website if someone contributes the code.

**Comment by SolalPirelli** [comment]
To add to this, the current MIT calculator numbers are also used in an odd way because they already include taxes yet the website subtracts the cost from the stipend to estimate what's left. Obviously, taxes don't work like that, if your pay is higher you'll pay more taxes.

How easy would it be, for US universities, to compute the expected tax that a single person with no dependents and no special situation needs to pay given a salary?

**Comment by noah-curran** [comment]
> How easy would it be, for US universities, to compute the expected tax that a single person with no dependents and no special situation needs to pay given a salary?

I don't think it would be too bad to compute this. The challenge is in collecting the 2023 tax brackets for each of the 50 states, and then subsequently updating these year after year.

**Comment by mjc0608** [comment]
This feature will not happen in the near future unless contributed by a volunteer.

**Comment by noah-curran** [comment]
@mjc0608 I think this issue should be left open so the request is not repeated and so we can keep track of such future needs for this project as we look at the long-term.

**Comment by ahoho** [comment]
I have big deadlines coming up but may try to take a stab over the summer. If anyone wants to take up the torch in the meantime, I've started the process in [this spreadsheet](https://docs.google.com/spreadsheets/d/10Vyhm4aAneC2CG1iW9tImm1bc-5gyz9Ba3uozFtKjVU/edit?usp=sharing).

**Comment by mjc0608** [comment]
Close due to inactivity. Any contribution is welcomed. Please reopen if anyone want to merge these data into this repo.
