### ISSUE TITLE
International fee column

### ISSUE THREAD

**Issue by naman** [CSStipendRankings/CSStipendRankings#53]
Hi! My university charges an additional $300 annually (including 100$ for summers). I was wondering if it will be a useful datapoint to collect as it causes an additional financial burden for international students.

**Comment by mjc0608** [comment]
This should be included in the Fees column.

**Comment by noah-curran** [comment]
@mjc0608 I don't think this should be in the fees column actually. I think the fees column should be reserved for costs that impact *all* grad workers. It is useful to separate such a fee that impacts only a subset of grad workers so that people can be informed.

**Comment by mjc0608** [comment]
I suppose there will be many fees that only impact a subset of grad workers, and we cannot have one column for each of them. Also, I think it's important to keep the UI and our database as simple as possible. What's your opinion @TonyZhangND @jiong-zhu

**Comment by noah-curran** [comment]
Maybe we should consider a revamp of the UI. Instead of a new column, we could set several toggles in a separate menu to let the user define themself demographically, and the costs (e.g., internal student fees, need to buy insurance) would adjust based on how the user responds. We would keep the columns how they are, but would change dynamically. This could help us generalize these sorts of needs in the future.

**Comment by TonyZhangND** [comment]
I don't think it is our goal to give a precise dissection of how much each individual will have to pay down to the dollar; that is simply unmaintainable. Rather, we want to give an idea of what QoL may be like.

In terms of fees, I suggest just listing the maximum of what one is expected to pay mandatorily, excluding optional costs such as enhanced dental insurance.

**Comment by noah-curran** [comment]
> I agree with @mjc0608  here. I don't think it is our goal to give a precise dissection of how much each individual will have to pay down to the dollar; that is simply unmaintainable, and very hard to verify. Rather, we want to give an idea of what QoL may be like.
> 
> 
> 
> In terms of fees, I suggest just listing the maximum of what one is expected to pay mandatorily, excluding optional costs such as enhanced dental insurance. If the university charges international students extra, that can be included in the overall fees.

OK - Fair enough. I can see your point of view. If this is the goal, then we can stick to it. Some may wonder what the fee breakdown for each school is. I wonder if we can consider such a breakdown instead? We could ask for it and include it as a tooltip.

**Comment by noah-curran** [comment]
To add: I think requiring this information would make the verification process better too.

**Comment by TonyZhangND** [comment]
Breakdown sounds good! 

@naman What university are you at and what is the total fees that you pay per year? I'll update the site with this info

**Comment by noah-curran** [comment]
Closing this issue in favor of #58

**Comment by naman** [comment]
@TonyZhangND I will fill out the Google Form with the information. UW-Madison, the total fee paid by international students is 300$ (International Student Fee) + 1903$ (Fees) and 600$ (for insurance)
