### ISSUE TITLE
No guaranteed funding and summer funding

### ISSUE THREAD

**Issue by naman** [CSStipendRankings/CSStipendRankings#54]
Hi! My CS department does not guarantee funding to "all" Ph.D. students (I don't have it) along with no summer funding. Moreover, the summer funding (not guaranteed) for TA and RA is different as TA appointments are shorter during the summers (4-week or 8-week courses). Can we have separate options for "no guarantee" funding status, and funding in TA vs RA?

**Comment by mjc0608** [comment]
Please submit via the form on the website. You will be asked to list the amount of summer funding, and whether it's guaranteed. In the future, we will have an option to only display guaranteed money.
