### ISSUE TITLE
Breakdown the total numbers in the fees column to include the various costs as a tool tip

### ISSUE THREAD

**Issue by noah-curran** [CSStipendRankings/CSStipendRankings#58]
We should have the fees column breakdown the costs associated to the fees. For instance, required health insurance, international student fees, or other university fees. Rather than separating the fees into their own columns, we can have a tool tip for each entry in order to breakdown the associated costs in order to be fully transparent about the final number.

Others have had disagreements about double-counting insurance, so this may make it so that those who feel the fees at a particular university may not apply to them can make a more informed decision about the data.

> > I agree with @mjc0608  here. I don't think it is our goal to give a precise dissection of how much each individual will have to pay down to the dollar; that is simply unmaintainable, and very hard to verify. Rather, we want to give an idea of what QoL may be like.
> > 
> > 
> > 
> > In terms of fees, I suggest just listing the maximum of what one is expected to pay mandatorily, excluding optional costs such as enhanced dental insurance. If the university charges international students extra, that can be included in the overall fees.
> 
> OK - Fair enough. I can see your point of view. If this is the goal, then we can stick to it. Some may wonder what the fee breakdown for each school is. I wonder if we can consider such a breakdown instead? We could ask for it and include it as a tooltip.

_Originally posted by @noah-curran in https://github.com/CSStipendRankings/CSStipendRankings/issues/53#issuecomment-1537573163_

**Comment by mjc0608** [comment]
This seems unlikely to happen, at least in the near future.
