### ISSUE TITLE
Stipend and Expense Data Collection in Open Source

### ISSUE THREAD

**Issue by animesh-garg** [CSStipendRankings/CSStipendRankings#60]
This is a wonderful resource that promotes transparency with the hope to encourage action that achieves equity in graduate student pay. 

However the data in this ranking measure is often opaque.

I recommend that you provide the option to users for 
- Including redacted offer letters or pay stubs -- this will lead to blue-check verified data points. 
- Also include large scale self-reported open source data.

The open source data collection can be setup using [Drafty](https://drafty.cs.brown.edu/)!
It could also be done as a Google Form with a results sheet that is open to view/download for all. 
The form could also include redacted uploads of the offer letters. 

This data transparency will help a lot and provide numbers which are reflective of the actuals.

**Comment by ahoho** [comment]
I think having sources for all the data points is a good idea.

One issue with self-reported data is that it will get stale, which is a problem when universities raise stipends (last time I checked the self-reported [phdstipends.com](http://www.phdstipends.com/results) median is below the minimum for my institution, even if filtering to recent years). There will also be an issue with small sample sizes.

Perhaps the right solution is to use self-reported data to collect the _proportion_ of people receiving summer funding (and whether it is half/quarter/full time), which presumably will remain somewhat fixed year-to-year? Then we could impute a distribution from the guaranteed minima in the offer letters.

**Comment by animesh-garg** [comment]
>One issue with self-reported data is that it will get stale, which is a problem when universities raise stipend

I agree with you. But, the current the data will also have a similar problem.
Besides current data is a single data point. And unless verified from written offer letter, can also lack authenticity!
Moreover, it adds burden of evaluation to the repo maintainers making this effort hard to sustain in a couple of years.

Ideally, the self-reported data can include time-frames and even redacted offer-letters/paystubs.
This information could be used to create aggregated estimates of monthly, 9-month, & summer stipends including some spreads.
And also yes to the proportion of students receiving summer support and how much f it should also be included.

**Comment by noah-curran** [comment]
I didn't see this separate issue until just now, but I left a related comment in https://github.com/CSStipendRankings/CSStipendRankings/issues/17#issuecomment-1540706309 that could contribute to this discussion. TL;DR: generally agree for the above, but I have concerns about self-reported spending.

**Comment by mjc0608** [comment]
Close due to inactivity. Also, this feature is also unlikely to be implemented unless contributed by a volunteer.
