### ISSUE TITLE
Vision and Dental

### ISSUE THREAD

**Issue by mjc0608** [CSStipendRankings/CSStipendRankings#63]
Should vision and dental insurance be counted as "Fees"?

**Comment by pyjhzwh** [comment]
I don't think so. It's more like an option that students could choose. For example, many students do not choose vision plan.

**Comment by noah-curran** [comment]
Agree with @pyjhzwh. I think the point of fees are costs that you have no control over.

As worded on the website, "non-reimbursible tariffs (including health insurance) reclaimed by said institution" maybe we should consider adding "mandated" or "required" to this statement to avoid confusion?
