### ISSUE TITLE
[Data Update]: University of Washington

### ISSUE THREAD

**Issue by emeryberger** [CSStipendRankings/CSStipendRankings#66]
> Please duplicate the block below for each institution you want to add or update.

## University of Washington

* [X] This updates an existing institution. 

- **Annual Stipend Amount (USD, both Pre-Qualification and Post-Qualification if different)**: 

$30,114

- **Annual Out-of-pocket Fees (and Health Insurance) Charged by University (USD)**:

$744

- **Summer Funding Guarantee**: (yes/no/don't know)

No

- **Source of the stipend and fee data (e.g., your own data point, a link to an official website, etc.)**: 

Attached redacted offer letter.

[UW_2003_funding.pdf](https://github.com/CSStipendRankings/CSStipendRankings/files/11456817/UW_2003_funding.pdf)

**Comment by mjc0608** [comment]
This amount seems for 9 months, and it looks like UW does not guarantee summer funding. We will remove the summer funding mark.

However, based on our knowledge (from a UW prof and a student), most students at UW actually get 2x stipends during the summer months (except for two weeks). We may still use the amount that the majority of students get, where the definitely of "majority" should be formalized on the website.

This actually opens a broader question: should we consider such stipend data as "verified"? Maybe we should use different checkmarks for verified 9-month stipends and verified 12-month stipends (like a gray one and a blue one).

**Comment by mjc0608** [comment]
Also, it seems like UW does not provide 100% of insurance, students may still need to pay something.

**Comment by emeryberger** [comment]
I think you will find that "most" will be a difficult standard to maintain transparently - you would need to collect a large amount of data. Prospective graduate students in my experience want to know what is guaranteed. I will note here that UWisc (at least until recently) made PhD offers with _no_ guarantees of funding. I'd stick to offer letters. If you do so, you can ensure accuracy and also put pressure on those departments that do not guarantee funding by making this visible in the rankings.

**Comment by emjun** [comment]
I will just add to this discussion from my experience as a PhD student at UW (who is about to graduate). People told me during Visit Days/Orientation that "most" students receive 2x summer funding, and that was misleading and missed important nuances across the department. My first advisor would not pay me 2x despite what others  in my larger research area were receiving. In fact, some research areas/groups have explicitly committed to not paying students double over the summer. Therefore, I would prioritize a "guarantee" in the rankings. A thought -- This would be substantially more work, but one could consider adding more "verified for these areas/faculty:..." tags/filters/options.

**Comment by mjc0608** [comment]
Thanks for your feedback @emjun

>I would prioritize a "guarantee" in the rankings.
This will hopefully be implemented in the next week or two, and will be enabled after we collect enough data.

>one could consider adding more "verified for these areas/faculty:..." tags/filters/options.
I think adding this will make the label system unmanageable, so it's unlikely to happen. I believe these details should be discussed between the advisor and the student. However, I believe having a functionality to show only guaranteed funding should help as well.

**Comment by mjc0608** [comment]
Got some official data from their website. I guess I'm going to use that one. What's others' opinion? https://grad.uw.edu/wp-content/uploads/2022-23-RA_salary_chart.pdf

**Comment by mjc0608** [comment]
I'm closing this issue because the current data is from their official RA salary chart.

We are now putting `summer-no-gtd` and 20 hrs for ECE, and `summer-no-gtd varies` and 40 hrs for CSE, based on reports from grad students at UW.
