### ISSUE TITLE
[Data Update]: UMD summer stipend update

### ISSUE THREAD

**Issue by mjc0608** [CSStipendRankings/CSStipendRankings#69]
## Institution name: University of Maryland - College Park

* [x] This updates an existing institution. 

- **Annual Stipend Amount (USD, both Pre-Qualification and Post-Qualification if different)**: pre-qual: 40527; post-qual: 43528

- **Source of the stipend and fee data (e.g., your own data point, a link to an official website, etc.)**: 
This data is from an official email from the department chair, Matthias Zwicker. According to the report, the department had 142 summer GRAs in 2022, where 26 of them are employed for 20h/week, 26 for 30h/week, and 90 for 40h/week. As a result, 80% of students enrolled in the summer get at least 30h/week GRA appointments.

The email is attached below:
[FY23 GA RATES COMP SCI_11-1-22_COLA_Final.pdf](https://github.com/CSStipendRankings/CSStipendRankings/files/11520840/FY23.GA.RATES.COMP.SCI_11-1-22_COLA_Final.pdf)
[UMD2022.pdf](https://github.com/CSStipendRankings/CSStipendRankings/files/11520841/UMD2022.pdf)

**Comment by mjc0608** [comment]
Website updated.

**Comment by ahoho** [comment]
The denominator is off---this doesn't include shares of students who were unfunded. We just ran an internal survey showing that one in four PhDs is unfunded for at least one summer.

**Comment by mjc0608** [comment]
We don't count students going for internships as "enrolled" in the summer. As a result, for the summer funding, the total number is 142, unless the department chair excludes students who stayed in the department but didn't get paid.

**Comment by ahoho** [comment]
> The department chair excludes students who stayed in the department but didn't get paid

Right, that's what's happening. They aren't on payroll so they don't have the data. Here's results from our internal survey (120 responses from PhDs):

Status | Summers | Pct.
-- | -- | --
No funding | 38 | 13%
20 hr/wk GA | 37 | 13%
30 hr/wk GA | 6 | 2%
40 hr/wk GA | 103 | 36%
Internship / external | 93 | 32%
Multi-year fellowship | 12 | 4%
Total | 289 | 100%

**Comment by mjc0608** [comment]
Is this for the current summer?

**Comment by mjc0608** [comment]
Can you upload redacted raw data here?

**Comment by ahoho** [comment]
I didn't ask for consent to share publicly when collecting the data, so I'm afraid I can't (in principle you could de-anonymize some individuals based on their funding history). 

This data is across all summers, but I can get it for the most recent summer (not immediately). The weighted average appointment is 27 hours based on the historical data, if excluding those with external funding (I don't think that's entirely fair, because the existence of department funding has an obvious causal effect on the choice to do an internship, but I do appreciate it is difficult to measure).

**Comment by mjc0608** [comment]
We can put an official survey on our website if you want (actually, we prefer doing that). Do you think it's possible to publish the raw data if we only collect data for the upcoming summer or summer 2022?

For summers, we do not count students doing internships and students who do not do research for personal reasons. However, I think we should count students under fellowships.

Once you have the data we can use the minimum stipend for at least 80% of students.

**Comment by zzylol** [comment]
May I ask how much the after-tax stipend will be? Thanks!

**Comment by mjc0608** [comment]
@ahoho any update on the summer data?

**Comment by mjc0608** [comment]
Close this issue due to inactivity. Please reopen if anyone has updates.
