### ISSUE TITLE
Might need to add year to the data points

### ISSUE THREAD

**Issue by jedyang97** [CSStipendRankings/CSStipendRankings#7]
Stipends change over time, adding a drop-down menu to select year to view data and also ask data point submitters to include year of data point might be helpful

<img width="644" alt="image" src="https://user-images.githubusercontent.com/12980222/236372854-85ed3f62-d0ad-4dff-bcf5-9f60e28d27e0.png">

**Comment by mjc0608** [comment]
This feature will not be implemented in the near future unless contributed by a volunteer.
