### ISSUE TITLE
Filtering options not working: Exclude summer stipend filters universities!

### ISSUE THREAD

**Issue by animesh-garg** [CSStipendRankings/CSStipendRankings#70]
Thanks a lot for improving the rankings and database so quickly. 
The currently toggle options `exclude summer stipend` filters universities. 

Is this expected behavior?
All schools listed in the option (1), should be included in this option as well with rescaled numbers. 

Moreover, suggestion to change language
(1) **Add Annual** the stipend received by the majority of students, 
(2) the minimal guaranteed stipend, and 
(3) the stipend that students receive during **academic year excluding summer**

**Comment by mjc0608** [comment]
>All schools listed in the option (1), should be included in this option as well with rescaled numbers.

Yes, but we don't have the data for a lot of schools.

>Moreover, suggestion to change language

Can you submit a pull request?
