### ISSUE TITLE
Stanford University was marked as a public university incorrectly.

### ISSUE THREAD

**Issue by MingkaiChen** [CSStipendRankings/CSStipendRankings#77]
Stanford is incorrectly labeled as a public university in the current data. However according to [Wikipedia](https://en.wikipedia.org/wiki/Stanford_University):

> Stanford University, officially Leland Stanford Junior University, is a **private** research university in Stanford, California.

I have already created a Pull Request #76 to correct this misinformation.

**Comment by mjc0608** [comment]
Close because #76 was merged
