### ISSUE TITLE
Clicking on check mark icons has no effect

### ISSUE THREAD

**Issue by emeryberger** [CSStipendRankings/CSStipendRankings#80]
Website says:

> [gray checkmark], indicating the stipend is verified for the semester time, but not for the summer. This icon is clickable and linked to the document used in verification.
> [blue checkmark], indicating the stipend is verified for 12 months. Similarly, it is linked to the document used in verification.

The checkmarks are just svgs with no surrounding span with an id (generated by iconify), and nothing in `csstipendrankings.js` looks anything like it's adding links to these. (I could be missing something, but clicking on them does nothing).

**Comment by mjc0608** [comment]
Hi Emery,

The checkmark is generated with [this code block](https://github.com/CSStipendRankings/CSStipendRankings/blob/main/js/csstipendrankings.js#L290). A `<span>` label is generated with some attributes, and iconify's js will replace it with SVGs.

For departments whose stipend verification is via a public GitHub issue (e.g., UPenn), `verified_status` will contain two elements: a string "Y" and a url showing the issue; in this case, an `<a>` label will be generated, which links to the issue. If the verification is through an offer letter uploaded through the Google form (e.g., Berkeley), we won't have a public url and the `<a>` label will not be generated.

(As you may see, our current implementation is really ugly.)

Best,
Jiacheng

**Comment by emeryberger** [comment]
Got it. Might want to update the language on the website.

**Comment by emeryberger** [comment]
(I had not known that we needed to post stipend letters as GitHub issues!)

**Comment by mjc0608** [comment]
> Might want to update the language on the website.

Just update the language a little bit. Hopefully it is clear now.
