### ISSUE TITLE
[Data Update]: University of Massachusetts Amherst offer letter

### ISSUE THREAD

**Issue by emeryberger** [CSStipendRankings/CSStipendRankings#82]
> Please duplicate the block below for each institution you want to add or update.

## Institution name: University of Massachusetts Amherst

* [X] This updates an existing institution. 

Uploaded offer letter.

- **Additional Comments (Optional)**: 

[UMass Admissions Letter.pdf](https://github.com/CSStipendRankings/CSStipendRankings/files/11937552/UMass.Admissions.Letter.pdf)

**Comment by mjc0608** [comment]
The summer income and verification are updated.
