### ISSUE TITLE
[Data Update]: The Ohio State University

### ISSUE THREAD

**Issue by efosler** [CSStipendRankings/CSStipendRankings#84]
> Please duplicate the block below for each institution you want to add or update.

## Institution name: The Ohio State University

* [ Y ] This updates an existing institution. 

- **Annual Stipend Amount (USD, both Pre-Qualification and Post-Qualification if different)**: $31,800 for most Ph.D. students.  TAs who still need to meet the minimum English proficiency required by the state have a stipend rate of $30,900; PhD students who have passed candidacy exams (ABD) have a $32,400 rate.  Rates effective Autumn 2023.

- **Annual Local Living Wage (USD)**: $33,937

  - **Link to the [MIT Living Wage Calculator](http://livingwage.mit.edu/)**: https://livingwage.mit.edu/counties/39049

    > Note: Please use The number in `Typical Expenses -> Required annual income before taxes -> 1 Adult & 0 Children` as the annual local living wage.

- **Annual Out-of-pocket Fees (and Health Insurance) Charged by University (USD)**: $1054

- **Summer Funding Guarantee**: (yes/no/don't know)  Not all students are guaranteed summer funding.  Many receive it, particularly if they have an RA, but many go on internship as well.  TA positions in summer are minimal.

- **Source of the stipend and fee data (e.g., your own data point, a link to an official website, etc.)**: I'm the Associate Chair for Academic Administration for the department and just set the rates in concert with the Chair and HR for AU24.  I don't directly have access to the fee information, but I asked one of my students and they provided a figure of $1054.

- **Additional Comments (Optional)**: 
All figures given for 12 month period; those with 9 month appointments receive correspondingly less.

**Comment by mjc0608** [comment]
Thanks. We have updated the website.
