### ISSUE TITLE
[Question] What to pick when academic year (two semesters) is guaranteed but summer is not? What stipend to list?

### ISSUE THREAD

**Issue by Delta-Sigma** [CSStipendRankings/CSStipendRankings#86]
The site lists three kinds of tags:
1. summer-gtd, indicating summer funding is guaranteed in this department.
2, varies, indicating the amount of funding varies from advisor to advisor in this department.
3. no-guarantee, indicating this department does not guarantee any funding at all.

I believe the situation where academic year is guaranteed but summer isn't is not captured by these.

Also, what should be in the stipend column for such a situation? I think only the academic year should be included.

**Comment by mjc0608** [comment]
If the academic year is guaranteed but summer is not, then the department does not have any label. In such case, please enter the amount of money that you believe that 80% of students can get in the stipend column, and enter the amount of summer funding in the summer column.
