### ISSUE TITLE
[Data Update]: UW-Madison Stipend Amount

### ISSUE THREAD

**Issue by cpsiff** [CSStipendRankings/CSStipendRankings#88]
## Institution name: University of Wisconsin - Madison

* [x] This updates an existing institution. 

- **Annual Stipend Amount (USD, both Pre-Qualification and Post-Qualification if different)**:
  - Pre-qual: $34,097
  - Post-qual: $36,074
  - Post-prelim (thesis proposal): $38,074

- **Annual Local Living Wage (USD)**: $36,371

- **Annual Out-of-pocket Fees (and Health Insurance) Charged by University (USD)**: $1,903

- **Summer Funding Guarantee**: no

- **Source of the stipend and fee data (e.g., your own data point, a link to an official website, etc.)**: [official website](https://grad.wisc.edu/wp-content/uploads/sites/329/2023/04/Stipend-rates-FY24_final082323.pdf)

- **Additional Comments (Optional)**: I believe some students are admitted with a stipend guarantee (never for summer) and some are admitted without. No differentiation between MS and PhD student in admission (free to switch between).

**Comment by mjc0608** [comment]
Updated. Also, do you know how much of these stipends are from summer?

**Comment by cpsiff** [comment]
You can compare the "RA academic" column to "RA annual" to see that it goes from $25,555 (pre qual) to $34,067 (pre qual), so $8,512 for summer (pre qual)

**Comment by mjc0608** [comment]
Thanks, the summer stipends were updated.

**Comment by mjc0608** [comment]
Some additional information that you may want to know about UW Madison:
1. Fees are updated from #100 
2. UW Madison's funding guarantee policy #96

**Comment by naman** [comment]
There was a minor discrepancy in the annual RA funding $34,067 (was $34,097 in this PR). I have also updated the Living Cost from $36371 to 44962 #105
