### ISSUE TITLE
[Data Update]: NC State University Stipend amount

### ISSUE THREAD

**Issue by Nyovelt** [CSStipendRankings/CSStipendRankings#90]
> Please duplicate the block below for each institution you want to add or update.

## Institution name: 

* [x] This updates an existing institution. 

- **Annual Stipend Amount (USD, both Pre-Qualification and Post-Qualification if different)**: $23,400 ($2,600/mo)

- **Annual Local Living Wage (USD)**:

  - **Link to the [MIT Living Wage Calculator](http://livingwage.mit.edu/)**: 

    > Note: Please use The number in `Typical Expenses -> Required annual income before taxes -> 1 Adult & 0 Children` as the annual local living wage.

- **Annual Out-of-pocket Fees (and Health Insurance) Charged by University (USD)**:

- **Summer Funding Guarantee**: (yes/no/don't know)

- **Source of the stipend and fee data (e.g., your own data point, a link to an official website, etc.)**: my own data point

- **Additional Comments (Optional)**: The stipend duration is nine months; all other details remain unchanged from the current dataset.

**Comment by mjc0608** [comment]
This is significantly lower than the current data. Do you have a proof (such as an offer letter) so we can make the data verified? Also, do you have data for the 3-month summer income?

**Comment by Nyovelt** [comment]
Here is the [verification](https://webresources.aaaab3n.moe/share/NCSU_STIPEND.pdf)

And I do not have the data for the 3-month summer income.

**Comment by mjc0608** [comment]
Thanks. The data has been updated
