### ISSUE TITLE
[Data Update]: Yale University Stipend Amount

### ISSUE THREAD

**Issue by ChenLiu-1996** [CSStipendRankings/CSStipendRankings#92]
## Institution name: 

* [x] This updates an existing institution. 

- **Annual Stipend Amount (USD, both Pre-Qualification and Post-Qualification if different)**: 40,530

- **Annual Local Living Wage (USD)**: 36,753

  - **Link to the [MIT Living Wage Calculator](http://livingwage.mit.edu/)**: 

    > Note: Please use The number in `Typical Expenses -> Required annual income before taxes -> 1 Adult & 0 Children` as the annual local living wage.

- **Annual Out-of-pocket Fees (and Health Insurance) Charged by University (USD)**:

- **Summer Funding Guarantee**: yes

- **Source of the stipend and fee data (e.g., your own data point, a link to an official website, etc.)**: Internal email to all PhD students in the Graduate School of Arts and Sciences from the Dean.

- **Additional Comments (Optional)**: 
<img width="300" alt="yale-stipend-2023" src="https://github.com/CSStipendRankings/CSStipendRankings/assets/36081734/af5ff62a-2a93-4a73-9ca4-c47eff891528">

**Comment by mjc0608** [comment]
This was updated. Do you know whether yale guarantee summer funding?

**Comment by ChenLiu-1996** [comment]
> This was updated. Do you know whether yale guarantee summer funding?

I would believe so even though it is not explicitly stated on the offer or latest notice. I got the regular amount of biweekly stipend over the summer.
