### ISSUE TITLE
Add stipend data for Canada, Australia, Hong Kong, and Singapore.

### ISSUE THREAD

**Issue by aotzu** [CSStipendRankings/CSStipendRankings#94]
Many schools in these countries have open data about their stipends. I think adding them would be a good idea.

https://uwaterloo.ca/environment/graduate/future-graduate-students/funding-packages/funding-domestic-doctoral-students#:~:text=All%20full%2Dtime%20doctoral%20students,standing%20is%20%2425%2C962%20per%20year.

https://www.monash.edu/study/fees-scholarships/scholarships/find-a-scholarship/research-training-program-scholarship

https://www.gs.cuhk.edu.hk/admissions/scholarships-fees/scholarships

https://fass.nus.edu.sg/prospective-students/graduate/research/scholarships/nus-research-scholarship/

**Comment by mjc0608** [comment]
We don't have plan for these countries in the near future if not contributed. I'm closing this issue.
