### ISSUE TITLE
[Data Update]: Yale stipend adjustment

### ISSUE THREAD

**Issue by tangxiangru** [CSStipendRankings/CSStipendRankings#95]
> Please duplicate the block below for each institution you want to add or update.

## Institution name: Yale University

* [x] This updates an existing institution. 

- **Annual Stipend Amount (USD, both Pre-Qualification and Post-Qualification if different)**: 

Humanities/Social Sciences/Physical Sciences/Engineering: $48,330 stipend (19.2% increase)

CS is included in Engineering.

- **Source of the stipend and fee data (e.g., your own data point, a link to an official website, etc.)**: 

https://provost.yale.edu/news/announcing-ratified-local-33-contract

**Comment by mjc0608** [comment]
This link does not provide an exact number. Do you have another source?

**Comment by tangxiangru** [comment]
Sure, here is the attachment. 
![image](https://github.com/CSStipendRankings/CSStipendRankings/assets/22478336/731700fc-3845-4e64-91f8-3992ad15418e)

**Comment by mjc0608** [comment]
Also, do you have any information about the summer stipend and whether the summer stipend is guaranteed?

**Comment by LongfeiQiu2021** [comment]
We don't have special "summer stipend". The annual stipend is paid in 24 parts, twice a month.

**Comment by mjc0608** [comment]
Thanks. I have two additional questions:
1. How many month are considered as summer time at Yale?
2. By having "no special summer stipend", does it mean everyone who stays in the department during summer get the stipend?

**Comment by mjc0608** [comment]
Close due to inactivity.

**Comment by SudattaHor** [comment]
Hi, the Yale PhD stipend seems to be out of date. Please see the following link:

https://gsas.yale.edu/resources/graduate-financial-aid/phd-stipends

**Comment by mjc0608** [comment]
@SudattaHor Can you submit a pull request?
