### ISSUE TITLE
[Data Update]: Washington University in St. Louis

### ISSUE THREAD

**Issue by doopersooper** [CSStipendRankings/CSStipendRankings#97]
> Please duplicate the block below for each institution you want to add or update.

## Institution name: Washington University in St. Louis

* [X ] This updates an existing institution. 

- **Annual Stipend Amount (USD, both Pre-Qualification and Post-Qualification if different)**: 38500

- **Annual Local Living Wage (USD)**: 33244

  - **Link to the [MIT Living Wage Calculator](http://livingwage.mit.edu/)**: https://livingwage.mit.edu/metros/41180

    > Note: Please use The number in `Typical Expenses -> Required annual income before taxes -> 1 Adult & 0 Children` as the annual local living wage.

- **Annual Out-of-pocket Fees (and Health Insurance) Charged by University (USD)**: 0

- **Summer Funding Guarantee**: yes

- **Source of the stipend and fee data (e.g., your own data point, a link to an official website, etc.)**: Offer letter attached
[washu_offer-redacted.pdf](https://github.com/CSStipendRankings/CSStipendRankings/files/14212276/washu_offer-redacted.pdf)

- **Additional Comments (Optional)**:

**Comment by mjc0608** [comment]
updated
